# Generated by Django 5.2 on 2025-04-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
