# Generated by Django 5.2 on 2025-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ghlauthcredentials_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
